language: go
go:
    - 1.6

before_install:
  - go get golang.org/x/tools/cmd/cover
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - go test ./... -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -repotoken=CAMtsMCP5xATW2Gav1kuPOTefCmfjHsUX
